# Site settings
title: nouritsu
email: ab@nouritsu.com
description: >-
  Aneesh Bhave (nouritsu)'s blog and portfolio. Featuring articles on programming, technology and personal reflections
baseurl: ""
url: "https://nouritsu.com/"
github_username: nouritsu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Collections (for future use)
collections:
  posts:
    output: true
    permalink: /:collection/:name/
  pages:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
