name: Build Jekyll Site and Deploy to Hostinger FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout/@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true
      
      - name: Install Jekyll & Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy Site
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USR }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: ${{ secrets.FTP_DIR }}/
          local-dir: ./_site/
          
    
